In [ ]:
import yaml
config_file = 'config/config.yaml'

with open(config_file, 'r') as file:
    data = yaml.safe_load(file)

In [3]:
data

{'DATA_URL': {'SMALL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest-small.zip',
  'FULL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest.zip'},
 'DATA_DIR': {'DATA_100K': {'RAW': 'data/100k/raw/',
   'TRAIN': 'data/100k/train/ratings.csv',
   'TEST': 'data/100k/test/ratings.csv',
   'EVAL': 'data/100k/eval/ratings.csv',
   'SPLITS': [0.7, 0.15, 0.15],
   'N_USERS': 610,
   'N_MOVIES': 9724},
  'DATA_10M': {'RAW': 'data/10M/raw/',
   'TRAIN': 'data/10M/train/ratings.csv',
   'TEST': 'data/10M/test/ratings.csv',
   'EVAL': 'data/10M/eval/ratings.csv',
   'SPLITS': [0.8, 0.1, 0.1],
   'N_USERS': 330975,
   'N_MOVIES': 86000}}}

In [4]:
from src.data_pipeline.get_data import GetData

dataset_url = data['DATA_URL']['SMALL_URL']
dataset_path = data['DATA_DIR']['DATA_100K']['RAW']

dataset_name = 'ml-latest.zip'

In [5]:
gd = GetData(
    dataset_url=dataset_url,
    dataset_path=dataset_path,
    dataset_name=dataset_name
)


gd.get_data()

Dataset already downloaded and extracted.

In [6]:
dataset_path

'data/100k/raw/'

In [7]:
import os

'ratings.csv' in os.listdir(dataset_path)

True

In [8]:
import pandas as pd

d_path = os.path.join(data['DATA_DIR']['DATA_100K']['RAW'], 'ratings.csv')
df = pd.read_csv(d_path)
df

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [9]:
df = df.sample(frac=1.0, random_state=46)
df_grouped = df.groupby('userId').agg(list)
df_grouped

,movieId,rating,timestamp
userId,,,
1,"[1219, 216, 2137, 1136, 1517, 1220, 2654, 1573...","[2.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[964983393, 964981208, 964982791, 964981327, 9..."
2,"[58559, 79132, 48516, 115713, 74458, 109487, 1...","[4.5, 4.0, 4.0, 3.5, 4.0, 3.0, 5.0, 3.5, 2.5, ...","[1445715141, 1445714841, 1445715064, 144571485..."
3,"[1272, 1275, 1093, 7991, 2105, 2018, 1302, 723...","[0.5, 3.5, 0.5, 5.0, 2.0, 0.5, 0.5, 0.5, 0.5, ...","[1306463624, 1306463323, 1306463627, 130646368..."
4,"[2359, 904, 1288, 1046, 2599, 595, 4260, 4381,...","[4.0, 4.0, 4.0, 5.0, 5.0, 3.0, 2.0, 3.0, 2.0, ...","[964622590, 945079837, 945079653, 945173654, 9..."
5,"[349, 36, 21, 380, 150, 58, 474, 50, 110, 457,...","[3.0, 4.0, 4.0, 2.0, 3.0, 5.0, 4.0, 4.0, 4.0, ...","[847434832, 847435292, 847435238, 847434748, 8..."
...,...,...,...
606,"[8501, 1674, 3632, 1958, 3910, 4356, 44195, 31...","[4.0, 4.0, 4.0, 4.0, 4.0, 5.0, 4.0, 4.0, 4.0, ...","[1171369185, 1171754630, 1171501155, 117137701..."
607,"[3114, 1270, 1219, 1982, 110, 2097, 2194, 2918...","[3.0, 3.0, 3.0, 5.0, 5.0, 5.0, 5.0, 3.0, 4.0, ...","[963079100, 964744367, 963079420, 963079496, 9..."
608,"[673, 2723, 3439, 8366, 5669, 3114, 318, 596, ...","[3.0, 1.0, 2.0, 4.0, 3.5, 2.5, 4.5, 0.5, 3.5, ...","[1117504613, 1117504736, 1117506745, 111733693..."
609,"[1161, 592, 434, 613, 329, 828, 116, 137, 110,...","[4.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, ...","[847221080, 847220802, 847220907, 847221025, 8..."
610,"[6820, 85788, 112818, 1682, 144976, 98809, 686...","[4.0, 3.5, 3.0, 5.0, 4.5, 3.5, 4.5, 3.0, 3.5, ...","[1493848224, 1493849748, 1493848354, 147954301..."

In [10]:
for row in df_grouped.iterrows():
    print(len(row[1]))
    print(len(row[1].values[0]))
    print(len(row[1].values[1]))
    print(row[1].values[0]
    )

    break

3
232
232
[1219, 216, 2137, 1136, 1517, 1220, 2654, 1573, 1240, 1804, 3744, 296, 2193, 1270, 2993, 1089, 2273, 2997, 2640, 1580, 954, 2395, 1927, 50, 2542, 110, 1587, 2580, 441, 2478, 2648, 736, 1282, 2916, 2899, 780, 6, 2141, 2291, 1210, 2000, 592, 3809, 2414, 231, 2692, 1278, 2502, 2161, 3253, 2596, 2459, 3450, 2949, 3243, 2058, 356, 3034, 1793, 3703, 596, 3489, 101, 2353, 1396, 2253, 316, 2872, 2947, 2093, 1206, 1197, 804, 2094, 2991, 1920, 3247, 2078, 1031, 2139, 1090, 919, 1954, 1196, 1224, 2761, 457, 1030, 2641, 2959, 1092, 2033, 1552, 2571, 2329, 1080, 2616, 1198, 1073, 5060, 2944, 3702, 2528, 2617, 1265, 3052, 70, 943, 2470, 1222, 2644, 2105, 1024, 1226, 1348, 3729, 661, 1029, 163, 1042, 2054, 500, 1967, 593, 423, 2005, 2657, 1617, 3441, 2090, 157, 2985, 940, 1275, 47, 923, 362, 3168, 2716, 151, 1, 1620, 2018, 3793, 590, 1732, 2406, 1097, 1023, 2096, 1644, 1127, 2028, 3439, 1473, 608, 2529, 1625, 1208, 2797, 1032, 2143, 3671, 2826, 527, 3440, 2338, 553, 3147, 543, 1213, 1445, 2099, 3062, 2427, 1049, 1777, 3053, 3176, 1676, 3448, 3639, 2115, 3386, 2046, 2366, 2116, 1408, 3527, 2389, 480, 2492, 1377, 552, 2174, 1291, 2387, 3033, 2268, 367, 1025, 3740, 3, 1060, 1009, 333, 2948, 3578, 1805, 4006, 2858, 2700, 1258, 673, 260, 349, 648, 3273, 223, 1256, 2628, 235, 3617, 2012, 1298, 3479, 2048, 2450, 1214, 733, 2987, 1500]

In [11]:
c = [v[:5] for v in row[1].values]

for w, ww, www in zip(*c):
    print(w)
    print(ww)
    print(www)


print(c)

1219
2.0
964983393
216
5.0
964981208
2137
5.0
964982791
1136
5.0
964981327
1517
5.0
964981107
[[1219, 216, 2137, 1136, 1517], [2.0, 5.0, 5.0, 5.0, 5.0], [964983393, 964981208, 964982791, 964981327, 964981107]]

In [12]:
data

{'DATA_URL': {'SMALL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest-small.zip',
  'FULL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest.zip'},
 'DATA_DIR': {'DATA_100K': {'RAW': 'data/100k/raw/',
   'TRAIN': 'data/100k/train/ratings.csv',
   'TEST': 'data/100k/test/ratings.csv',
   'EVAL': 'data/100k/eval/ratings.csv',
   'SPLITS': [0.7, 0.15, 0.15],
   'N_USERS': 600,
   'N_MOVVIES': 9000},
  'DATA_10M': {'RAW': 'data/10M/raw/',
   'TRAIN': 'data/10M/train/ratings.csv',
   'TEST': 'data/10M/test/ratings.csv',
   'EVAL': 'data/10M/eval/ratings.csv',
   'SPLITS': [0.8, 0.1, 0.1],
   'N_USERS': 330975,
   'N_MOVIES': 86000}}}

In [13]:
train_dataset_path = data['DATA_DIR']['DATA_100K']['TRAIN']
val_dataset_path = data['DATA_DIR']['DATA_100K']['EVAL']
test_dataset_path = data['DATA_DIR']['DATA_100K']['TEST']
splits = data['DATA_DIR']['DATA_100K']['SPLITS']

DESTINATION_PATHS = [train_dataset_path, val_dataset_path, test_dataset_path]

In [14]:
train_dataset_path

'data/100k/train/ratings.csv'

In [ ]:
from src.data_pipeline.processing_data import ProcessData


process_data = ProcessData(
    raw_data_path=d_path,
    destination_paths=['asda'],
    splits = [0.7],
    mode='user_time'
)


process_data.process()

AssertionError: The splits list needs 2 or 3 values

In [14]:
n = 0
m = 10 - n


((0.9) ** n ) * ((0.1) ** m)

1.0000000000000006e-10

In [16]:
((0.9) ** 5)

0.5904900000000001

In [1]:
import yaml
config_file = 'config/config.yaml'

with open(config_file, 'r') as file:
    data = yaml.safe_load(file)

In [2]:
data

{'DATA_URL': {'SMALL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest-small.zip',
  'FULL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest.zip'},
 'DATA_DIR': {'DATA_100K': {'RAW': 'data/100k/raw/',
   'TRAIN': 'data/100k/train/ratings.csv',
   'TEST': 'data/100k/test/ratings.csv',
   'EVAL': 'data/100k/eval/ratings.csv',
   'SPLITS': [0.7, 0.15, 0.15],
   'N_USERS': 610,
   'N_MOVIES': 9724},
  'DATA_10M': {'RAW': 'data/10M/raw/',
   'TRAIN': 'data/10M/train/ratings.csv',
   'TEST': 'data/10M/test/ratings.csv',
   'EVAL': 'data/10M/eval/ratings.csv',
   'SPLITS': [0.8, 0.1, 0.1],
   'N_USERS': 330975,
   'N_MOVIES': 86000}}}

In [3]:
import os

from src.data.processing_data import ProcessData
from src.models.autoencoders import AutoEncoder
from src.prediction.predict_items import PredictUserAllItems
from src.data.datasets import AutoEncoderDataset
from src.models.wrappers import AutoencoderWrapper

from torch.utils.data import DataLoader

In [4]:
N_USERS = data['DATA_DIR']['DATA_100K']['N_USERS']
N_ITEMS = data['DATA_DIR']['DATA_100K']['N_MOVIES']
TRAIN_DATASET_PATH = data['DATA_DIR']['DATA_100K']['TRAIN']
RAW_DATASET_PATH = os.path.join(data['DATA_DIR']['DATA_100K']['RAW'], 'ratings.csv')


autoencoder_dataset = AutoEncoderDataset(data_path=TRAIN_DATASET_PATH)
autoencoder_dataset_full = AutoEncoderDataset(data_path=RAW_DATASET_PATH)


autoencoder = AutoEncoder(
    io_features=N_ITEMS, hidden_dim=64
)

In [5]:
autoencoder_dataset[5].shape, autoencoder_dataset_full[5].shape

(torch.Size([7525]), torch.Size([9724]))

In [6]:
batch = next(iter(DataLoader(autoencoder_dataset_full, 64)))

In [7]:
autoencoder(batch).shape

torch.Size([64, 9724])

In [8]:
data

{'DATA_URL': {'SMALL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest-small.zip',
  'FULL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest.zip'},
 'DATA_DIR': {'DATA_100K': {'RAW': 'data/100k/raw/',
   'TRAIN': 'data/100k/train/ratings.csv',
   'TEST': 'data/100k/test/ratings.csv',
   'EVAL': 'data/100k/eval/ratings.csv',
   'SPLITS': [0.7, 0.15, 0.15],
   'N_USERS': 610,
   'N_MOVIES': 9724},
  'DATA_10M': {'RAW': 'data/10M/raw/',
   'TRAIN': 'data/10M/train/ratings.csv',
   'TEST': 'data/10M/test/ratings.csv',
   'EVAL': 'data/10M/eval/ratings.csv',
   'SPLITS': [0.8, 0.1, 0.1],
   'N_USERS': 330975,
   'N_MOVIES': 86000}}}

In [9]:
type(data['DATA_DIR']['DATA_100K']['SPLITS'][0])

float

In [10]:
type(data)

dict

In [11]:
autoencoder_wrapper = AutoencoderWrapper(
    model=autoencoder,
    config = {"lr": 0.001, "epochs": 10},
    optimizer_name='adam')

autoencoder_wrapper(batch)

tensor([[ 0.9820, -0.6737,  0.4245,  ..., -0.8900, -0.1347,  0.4424],
        [-0.0200,  0.1002, -0.5652,  ..., -0.0154,  0.1089,  0.2756],
        [ 0.2607,  0.1241,  0.2245,  ...,  0.0225,  0.1388,  0.2173],
        ...,
        [ 0.0756,  0.5476, -2.9094,  ..., -0.3605,  0.1993,  1.2961],
        [ 0.5545, -1.3427, -0.0520,  ..., -1.0895,  0.3379,  1.2792],
        [-0.2326,  0.7124, -0.6263,  ..., -1.5663,  0.1298, -0.0220]],
       grad_fn=<AddmmBackward0>)

In [12]:
autoencoder_wrapper.training_step(batch=batch, batch_idx=0)

c:\Users\ernes\miniconda3\envs\venv\Lib\site-packages\pytorch_lightning\core\module.py:451: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`

tensor(14.4977, grad_fn=<DivBackward0>)