In [1]:
import pandas as pd
import numpy as np
import yaml
import os

In [2]:
os.chdir('..')

In [3]:
config_path = os.path.join('config', 'config.yaml')

with open(config_path, 'r') as file:
    config = yaml.safe_load(file)
config

{'DATA_URL': {'SMALL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest-small.zip',
  'FULL_URL': 'https://files.grouplens.org/datasets/movielens/ml-latest.zip'},
 'DATA_DIR': {'DATA_100K': {'RAW': 'data/100k/raw/',
   'TRAIN': 'data/100k/train/ratings.csv',
   'TEST': 'data/100k/test/ratings.csv',
   'EVAL': 'data/100k/eval/ratings.csv',
   'SPLITS': [0.7, 0.15, 0.15],
   'N_USERS': 610,
   'N_MOVIES': 9724},
  'DATA_10M': {'RAW': 'data/10M/raw/',
   'TRAIN': 'data/10M/train/ratings.csv',
   'TEST': 'data/10M/test/ratings.csv',
   'EVAL': 'data/10M/eval/ratings.csv',
   'SPLITS': [0.8, 0.1, 0.1],
   'N_USERS': 330975,
   'N_MOVIES': 86000}}}

In [4]:
raw_file = os.path.join(config['DATA_DIR']['DATA_100K']['RAW'], 'ratings.csv')


ratings_df = pd.read_csv(raw_file)
ratings_df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [5]:
# dataset shape
ratings_df.shape

(100836, 4)

In [6]:
n_movies = ratings_df['movieId'].nunique()
n_users = ratings_df['userId'].nunique()


print(f'Number of movies in the dataset: {n_movies}')
print(f"Number of users in the dataset: {n_users}")

Number of movies in the dataset: 9724
Number of users in the dataset: 610

In [7]:
summary_movies_watched = (
    ratings_df
        [['userId', 'movieId']]
        .groupby('userId')
        .agg('count')
        .describe()
)
summary_movies_watched.columns = ['movies_watched']
summary_movies_watched

       movies_watched
count      610.000000
mean       165.304918
std        269.480584
min         20.000000
25%         35.000000
50%         70.500000
75%        168.000000
max       2698.000000

In [8]:
# ratings stats
ratings_df['rating'].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [9]:
# user id range
ratings_df['userId'].min(), ratings_df['userId'].max()

(np.int64(1), np.int64(610))

In [10]:
# movies id range
ratings_df['movieId'].min(), ratings_df['movieId'].max()

(np.int64(1), np.int64(193609))

In [23]:
for (idx, num) in enumerate(sorted(ratings_df['movieId'].unique()), 1):
    if idx % 1000 == 0:
        print(f"Movie ID: {num} - Index: {idx}")

Movie ID: 1302 - Index: 1000
Movie ID: 2661 - Index: 2000
Movie ID: 4019 - Index: 3000
Movie ID: 5651 - Index: 4000
Movie ID: 7753 - Index: 5000
Movie ID: 38061 - Index: 6000
Movie ID: 68319 - Index: 7000
Movie ID: 97858 - Index: 8000
Movie ID: 140481 - Index: 9000

The movies ID are not fully presented in the dataset. That means that the number of unique ids is not equal to the maximum value of movie id.